#@data/values
---
namespace: demo

triggermesh:
  accesskey: <your AccessKeyId from step 2>
  secretkey: <your AccessKeyId from step 2>

app:
  accesskey: <your AWS_ACCESS_KEY_ID from step 3 (different from the value in step 2!)>
  secretkey: <your AWS_SECRET_KEY_ID from step 3 (different from the value in step 2!)>
  sessionkey: <your SessionToken from step 2>

function_image: <(optional) writable image url repository>
bucket_arn:  <your bucket ARN from step 1 (Must be the full ARN including the region and account)>