api = "0.6"

[buildpack]
id           = "kn-fn/java-function"
name         = "Java Function Buildpack"
version      = "{{.version}}"
sbom-formats = ["application/vnd.syft+json"]

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]
  include-files = ["README.md", "bin/build", "bin/detect", "bin/main", "buildpack.toml", "VERSION"]

[[metadata.dependencies]]
id      = "invoker"
name    = "Java Invoker"
version = "0.0.1"
uri     = "https://storage.googleapis.com/cnr-functions-release/invokers/java/java-function-invoker-0.0.1.jar"
sha256  = "90e4c1466645c17415a457d7a71ae59a729110c0bf93e37a212e8cf56c124478"
stacks  = [ "io.buildpacks.stacks.bionic" ]
