api = "0.6"

[buildpack]
  id           = "kn-fn/python-function"
  name         = "Python Function Buildpack"
  version      = "{{.version}}"
  sbom-formats = ["application/vnd.syft+json"]

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[metadata]
  include-files = ["README.md", "bin/build", "bin/detect", "bin/main", "buildpack.toml", "VERSION"]
  pre-package = "./build.sh"

  [[metadata.dependencies]]
    id      = "invoker"
    name    = "Python Invoker"
    version = "0.0.3"
    uri     = "https://github.com/vmware-tanzu/function-buildpacks-for-knative/releases/download/python-invoker%2Fv0.0.4/pyfunc-invoker-0.0.4.tar.gz"
    sha256  = "427a0eacdbfde110fe4d85a32741dc47e4003b7f8b04c7fa2cf34873e66c8b51"
    stacks  = [ "io.buildpacks.stacks.bionic" ]
