api = "0.6"

[buildpack]
id       = "kn-fn/python-function"
name     = "Python Function Buildpack"
version  = "0.0.1"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[metadata.dependencies]]
id      = "invoker"
name    = "Python Invoker"
version = "0.0.1"
uri     = "https://storage.googleapis.com/cnr-functions-release/invokers/python/pyfunc-invoker-0.0.1.tar.gz"
sha256  = "317cccddfb9d0e2c9c77029b181246ff3d098125427fc963e990600e8487bbac"
stacks  = [ "io.buildpacks.stacks.bionic" ]
