name: Buildpack Tests
on:
  workflow_dispatch: {}
  push:
    paths:
    - 'buildpacks/**'
  schedule:
    - cron: '0 6 * * 1'

jobs:
  buildpack-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.8'
    - run: go version
    - name: Run Buildpack Tests
      run: make buildpack-tests
