name: Confidence Tests
on:
  # workflow_dispatch: {}
  # push:
  #   paths:
  #   - 'invokers/python/**'
  #   - 'rules.mk'
  #   - 'tools.mk'
  #   - 'version.mk'
  #   - 'invokers/Makefile'
  #   - 'invokers/rules.mk'
  schedule:
    - cron: '0 6 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: WIP
      run: 