name: Java Invoker
on:
  workflow_dispatch: {}
  push:
    paths:
    - 'invokers/java/**'
    - 'rules.mk'
    - 'tools.mk'
    - 'version.mk'
    - 'invokers/Makefile'
    - 'invokers/rules.mk'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Invoker Tests
      run: make invoker.java.tests
