name: Python Invoker
on:
  workflow_dispatch: {}
  push:
    paths:
    - 'invokers/python/**'
    - 'rules.mk'
    - 'invokers/Makefile'
    branches:
    - '**'
    tags:
    - 'python-invoker/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Invoker Tests
      run: make invoker.python.tests

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref,'refs/tags/python-invoker/')
    steps:
    - uses: actions/checkout@v2
    - name: Write credentials for GCS
      env:
        GS_SERVICE_KEY: ${{ secrets.GS_SERVICE_KEY }}
      run: printf '%s' "${GS_SERVICE_KEY}" > /tmp/cnr-gcs-secret.json
    - name: Write boto file
      env:
        GCS_BOTO: ${{ secrets.GCS_BOTO }}
      run: printf '%s' "${GCS_BOTO}" > ~/.boto
    - name: Build
      run: make invokers.python
    - name: Print Hash
      run: make python-invoker.print_sha
    - name: Publish Python invoker
      run: make invoker.python.publish
