name: Test Invokers
on:
  workflow_dispatch: {}
  push:
    paths:
    - 'invokers/python/**'
    - 'invokers/java/**'
    - 'rules.mk'
    - 'tools.mk'
    - 'version.mk'
    - 'invokers/Makefile'
    - 'invokers/rules.mk'
  schedule:
    - cron: '0 6 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Python Invoker Tests
      run: make invoker.java.tests
    - name: Run Java Invoker Tests
      run: make invoker.java.tests
