# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

name: vmware srp caller
on:
  workflow_dispatch: {}

jobs:
  src-call:
    runs-on: ubuntu-latest
    steps:
    - name: Check SRP Creds
      uses: ./.github/actions/srp-helper/check-srp-creds
      with:
        client-id: ${{ secrets.SRP_CLIENT_ID }}
        client-secret: ${{ secrets.SRP_CLIENT_SECRET }}
    - name: Install SRP
      uses: ./.github/actions/srp-helper/install
    - name: Initialize SRP
      uses: ./.github/actions/srp-helper/init
      with:
        client-id: ${{ secrets.SRP_CLIENT_ID }}
        client-secret: ${{ secrets.SRP_CLIENT_SECRET }}
    - name: Collect SRP
      uses: ./.github/actions/srp-helper/collect
      with:
        git-repos: .
    - name: Submit SRP
      uses: ./.github/actions/srp-helper/submit