# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

name: vmware srp caller
on:
  workflow_dispatch: {}

jobs:
  src-call:
    runs-on: ubuntu-latest
    steps:
    - name: Install SRP
      uses: ./.github/actions/srp-helper
      with:
        client-id: ${{ secrets.SRP_CLIENT_ID }}
        client-secret: ${{ secrets.SRP_CLIENT_SECRET }}